experiment_name: ${MLFLOW_EXPERIMENT_NAME:-mlops-boston}
seed: 42
split:
  test_size: 0.2
  shuffle: true

model:
  type: rf # rf | logreg
  params:
    n_estimators: 300
    max_depth: 8
    n_jobs: -1

dataset:
  name: boston

# Salidas
outputs:
  dir: artifacts