name: CD - Train & Deploy Model

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: |
          python src/mlops_example/train.py --config configs/train_config.yaml

      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: artifacts/
